version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tutorial-postgres
    environment:
      POSTGRES_DB: tutorial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tutorial-network

  backend:
    build:
      context: ./backend/TaskManagementApi
      dockerfile: Dockerfile
    container_name: tutorial-backend
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=tutorial_db;Username=postgres;Password=password"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - tutorial-network

  frontend:
    build:
      context: ./frontend/task-management-app
      dockerfile: Dockerfile
    container_name: tutorial-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - tutorial-network

volumes:
  postgres_data:

networks:
  tutorial-network:
    driver: bridge